### ISSUE TITLE
test results

### ISSUE THREAD

**Issue by juliangruber** [dominictarr/level-replicate#12]
I was seing some weird behavior with level-replicate and created a repo to reproduce:

https://github.com/juliangruber/level-replicate-test

Similarely to the level-merkle test, with `$ node test.js <number of parties>` you can spawn n processes that replicate a leveldb over tcp and each second one of the nodes stores a new value. Each node outputs on stdout when a new value gets added.

Additionally, the first node gets some initial state.

Can you see whether that's intended behavior (i.e. bad use case) or there's something wrong?

**Comment by nrw** [comment]
i've been working on this module quite a bit lately, so i feel equipped to answer.

one part is a bad use case, the rest is intended behavior.

data inserted before `replicate(db, 'repl', id)` is called is not replicated. this module works because it logs each change in a sublevel and sends that log to any connected streams. there was talk of writing a setup script that would read current data and create a log entry for it, but nobody has jumped on that job yet.

you see multiple writes in the 3 party case because when `B` gets an update from `A`, it sends that update over the stream connected to `C`. this is the expected behavior. each node will try to resolve its log with connected streams for each change.

**Comment by nrw** [comment]
note: i now see the talk of a setup script i'm recalling is in issue #2

**Comment by juliangruber** [comment]
thanks for the clarification!
