### ISSUE TITLE
Sync subset of keys

### ISSUE THREAD

**Issue by RangerMauve** [dominictarr/level-replicate#22]
It'd be nice if there was an option to only synchronize a subset of the DB so that I'd be able to just pull the data that's relevant.

For example, if one db has

```
a:a
a:b
b:b
```

and another just cares about synchronizing keys that are in the range `a:a - a:z` and ignore any other keys.

It'd be nice if there was either some hooks into the sync process to call a callback to determine whether a key should be sent to the other side or not. Or maybe if there was a way to just specify a range.

Am I asking too much? Or maybe would this be accomplished better with some fancy sublevel magic?

**Comment by dominictarr** [comment]
I'm afraid this would be a non-trivial change.

This algorithm has efficient replication because all the keys are in the same set, and so it's easy to reason about which keys you have and don't have, just by sending a vector clock. (the latest sequence received from each author)

You could design a replication protocol that worked like you say, but it's be an entirely different design and not as simple. At least, it would be complex if you wanted to replicate changing subsets. If you always wanted to replicate the same subset then you could just use level replicate within sublevels and that would probably be okay.

I'm afraid there is no such thing as general purpose data replication...

**Comment by RangerMauve** [comment]
Fair enough.  I'm just getting started on learning about replication. Would you happen to have any resources that could help me come up with an algorithm for handling changing subsets? 

In the meantime, I think the thing I want to do could probably be implemented with sublevels. The only concern is that I'd want to have several sublevel instances for different keyspaces and I'm not sure off the top of my head if I'd need multiple connections for that to work smoothly.

**Comment by dominictarr** [comment]
unfortunately I do not know of any book etc that deals with the subject as a whole.
basically, the key part of data replication is a _remote set compairson_.  you need to efficiently compare the data you have with the data they have, without sending it all, which would defeat the point. (and once you have performed the remote comparison, you just send the extra data. easy)

This project is based on ideas i found in this paper: http://www.cs.cornell.edu/home/rvr/papers/flowgossip.pdf

Otherwise if you want to learn about data replication, i think the only way is studying the various algorithms. checkout scuttlebutt, git, rsync, couchdb.

**Comment by RangerMauve** [comment]
Yeah, I've come across the gossip paper before, haven't studied it in detail yet, though. Thanks for the help! I'll probably post here if I end up making anything neat. :D

**Comment by dominictarr** [comment]
cool! Also come hang out in the irc channel #stackvm and #scuttlebutt there are lots of other people interested in this stuff there

**Comment by RangerMauve** [comment]
Awesome, thanks!
